try{
    console.log('success')
}catch(err){
    console.log(err)
}